import { useState } from 'react';
import { Camera, ArrowUpRight, CircleHelp, FileText, Upload } from 'lucide-react';
import type { UrbanEvent } from '../types';
import { apiClient } from '../services/api';
import { UserGuideModal } from '../components/UserGuideModal';

export function IncidentsView({events,onSelectEvent,onOpenReport}:{events:UrbanEvent[];onSelectEvent:(event:UrbanEvent)=>void;onOpenReport?:(event:UrbanEvent)=>void}){
 const incidents=events.filter(e=>['hit_and_run','rash_driving','wrong_way','vehicle_violation','incident'].includes(e.event_type));
 const plates=incidents.filter(e=>e.extra_metadata?.plate_number);
 const [scanning,setScanning]=useState(false); const [scan,setScan]=useState<any>(null); const [error,setError]=useState(''); const [showGuide,setShowGuide]=useState(false);
 async function scanPlate(file?:File){if(!file)return;setScanning(true);setError('');setScan(null);try{setScan(await apiClient.detectAnpr(file));}catch(e){setError(e instanceof Error?e.message:'ANPR scan failed');}finally{setScanning(false);}}
 return <div className="analytics-page"><div className="page-heading"><div><div className="eyebrow">CHECK VEHICLE INCIDENTS</div><h1>See the story behind an alert<span>.</span></h1><p>Review unsafe driving reports, check photos, and read recorded number plates.</p></div><Camera size={28}/></div>
 {showGuide&&<UserGuideModal kind="anpr" onClose={()=>setShowGuide(false)}/>}<section className="panel analytics-section"><div className="section-heading"><h2>Live ANPR scanner</h2><div className="guide-actions"><button type="button" className="guide-trigger" onClick={()=>setShowGuide(true)} aria-haspopup="dialog"><CircleHelp size={16}/>How to use</button><Camera size={20}/></div></div><p className="empty-copy">Upload a clear vehicle or number-plate photo. Low-confidence results are flagged for manual verification.</p><label className="btn btn-secondary"><Upload size={15}/>{scanning?'Scanning… please wait':'Upload & scan plate'}<input type="file" accept="image/*" hidden disabled={scanning} onChange={e=>scanPlate(e.target.files?.[0])}/></label>{scanning&&<p className="empty-copy">The free cloud CPU may take about one minute. Keep this page open.</p>}{error&&<p className="empty-copy">{error}</p>}{scan&&<div className="incident-simple"><span className="number-plate"><small>IND</small>{scan.plate_number}</span><p>OCR confidence: {Math.round(scan.ocr_confidence*100)}% · Overall: {Math.round(scan.overall_confidence*100)}%</p><small>{scan.is_format_valid?'Indian plate format matched':'Format not verified'} · {scan.requires_manual_verification?'Manual verification required':'Verified by pipeline'} · {scan.mode}</small>{scan.warning&&<p className="empty-copy">{scan.warning}</p>}</div>}</section>
 <div className="analytics-columns"><section className="panel analytics-section"><div className="section-heading"><h2>Reported incidents</h2><span>{incidents.length} reports</span></div>{incidents.map(e=><article className="incident-simple" key={e.id}><span className={`badge badge-${e.severity}`}>{e.severity==='critical'?'urgent':e.severity}</span><h3>{e.event_type.replaceAll('_',' ')}</h3><p>{e.description}</p><small>Bus {e.bus_id}{e.is_simulated?' · Demo data':''}</small><div><button className="btn btn-secondary" onClick={()=>onSelectEvent(e)}>See details <ArrowUpRight size={14}/></button>{onOpenReport&&<button className="btn btn-ghost" onClick={()=>onOpenReport(e)}><FileText size={14}/>Open report</button>}</div></article>)}{!incidents.length&&<p className="empty-copy">No vehicle incidents to show yet.</p>}</section><section className="panel analytics-section"><div className="section-heading"><h2>Recorded number plates</h2><Camera size={20}/></div><p className="empty-copy">AI can make mistakes when reading plates. Check the original photo before taking action.</p>{plates.map(e=><button className="plate-record" key={e.id} onClick={()=>onSelectEvent(e)}><span className="number-plate"><small>IND</small>{e.extra_metadata?.plate_number}</span><span>Bus {e.bus_id} · {e.is_simulated?'Demo report':'Open details'} <ArrowUpRight size={15}/></span></button>)}{!plates.length&&<p className="empty-copy">No number plates have been recorded.</p>}</section></div></div>;
}
export default IncidentsView;
